language: ruby
rvm:
- 2.2.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  app: recordz-ror
  run: rake db:migrate
  api_key:
    secure: gvt9vvqA6+tC9J9PKjIBYsYVfnqZjjcoKQMutc7/HJN2gRKu5eCJxzOdUXoMlxm68W7O7STTCg7dwbrAkVSph1Ni5VopJot4sOO5OtXnQQ1By1BzmGdK/yGtcYxewV9n2/tKzAMUmn8llxZ/URxG5iXRAqvRtpg7VBpogJNPiKI=  
  on:
    repo: AnttiKotiranta/Recordz-RoR

